### ISSUE TITLE
Import tables from websites

### ISSUE THREAD

**Issue by spidfire** [amisarca/Sublime-Text-2-Table-Cleaner#4]
I like this plugin butI miss a little feature when i try to import data from the web.

I guess it can be done just by copying the clipboard and replacing all the \t (tabs) with | (pipes) and start and end a row with a |. 
And after this running the great formatting tool.

This would be a great addition

**Comment by amisarca** [comment]
Hi @spidfire , 

Thanks for pointing out this issue. Are you using tab indentation? As when I am copying a table, it is placing spaces instead of tabs. 

Can you give me a link of a table you worked with, and maybe a screenshot of how it looks like in Sublime?

Regards,
Andrei

**Comment by spidfire** [comment]
http://jsfiddle.net/g3KcJ/
I've created a table in jsfiddle.
just made a selection around the items. 
and made a quick video of it:
http://www.youtube.com/watch?v=SQYmdwOM0cY

(btw i'm using windows and google chrome)

**Comment by amisarca** [comment]
Hi @spidfire ,

Thanks for the video and the screenshot. 

As I guessed, you are using tabs for indentation, and that's why the cells are separated by tabs.
I will include the feature of replacing tabs with pipes in the next release (I am working on it, so it should be available soon), but unfortunately it won't be a general solution (for those who use spaces for indentation it won't work).

**Comment by amisarca** [comment]
In the latest version, if you press alt+shift+; then the table is aligned as you described.
